### PR TITLE
Use pin_project_lite

### PR DESCRIPTION
**Pull request by leshow**
FYI: This is branched off of my other PR

I'm far from a pin expert. I made the necessary changes and fixed all the compiler errors. It appears to pass the tests without issue. 

Does anyone have more experience with pinning that can comment on this? The `pin_project` macro implements Unpin for us already. AFAIK, we use the `#[pin]` macro on each of the fields that require pinning (what used to be `unsafe_pinned` with `pin-utils`), then make sure you use `project` to access the structs fields in it's implementation. I think that's it?

### CODE REVIEW

**Comment by mre** [comment]
> The pin_project macro implements Unpin for us already. AFAIK, we use the #[pin] macro on each of the fields that require pinning (what used to be unsafe_pinned with pin-utils), then make sure you use project to access the structs fields in it's implementation. I think that's it?

I think you're right. But probably other people like @wngr could elaborate on this.

Rebased on top of master now. I think this is mergeable now.
As I was reading through the changes, I found a comment with an issue on `futures-rs`:
https://github.com/rust-lang-nursery/futures-rs/issues/1475
Perhaps that was the reason why `futures-rs` used `pin` here in the first place. The issue has since been closed with a fix provided by @taiki-e.

So an alternative approach might be to use the new version of the `Chunks` adapter from here: https://github.com/rust-lang/futures-rs/blob/4613193023dd4071bbd32b666e3b85efede3a725/futures-util/src/stream/chunks.rs.
My gut feeling tells me that we should consider doing that instead, because this way, we don't diverge too much from `futures-rs` and could benefit from upstream changes in the future.
What do you think?

Sorry for noticing this so late.

**Comment by leshow** [comment]
I had no idea `Chunks` was available in the futures crate. Yeah, I think we could use it, or have our `ChunksTimeout` be the composition of `Chunks` plus the `Option<Delay>` field we need. I think we will still need `#[pin]` though, since we pin the `clock` field currently. I could mess around with this next time I get a bit of free time and see if we can't depend more on what's in `futures`.

**Comment by leshow** [comment]
I've played around with `Chunks` out of futures a bit and I'm afraid it's not really suitable for `futures-batch` to use. If you try to have a type like:

```rust
struct ChunksTimeout<St: Stream> {
   chunks: Chunks<St>,
   clock: Option<Delay>,
   duration: Duration
}
```

When you try to construct this type, you can't use `Chunks::new()` because it is not exported publicly. Which--fine, just construct it manually, but then when you try to access `chunks.cap` or `chunks.stream`, those fields are unavailable because they aren't public. There are no methods to access them either. All in all, I don't see how it's possible we could re-use the code in `futures`. The crate is really not constructed to give access to it's members outside the very well defined ways you're supposed to interact with the Stream/Future (i.e. `poll()`).

**Comment by mre** [comment]
I see multiple ways to stay in sync with `futures`:
1. We create a PR for `futures` to make `Chunks` and all other required types public. This way, we could use these types in our crate. I doubt that this PR would get accepted, though as the `futures` team might not want to commit to that API being public.
2. We copy-and-paste the new version of `Chunks` from the `futures` crate into `futures-batch`. This is the way we did it previously when we created the `futures-batch` crate. It should be straightforward, but of course we don't benefit from upstream improvements.
3. We move the `futures-batch` code into `futures` altogether. We could use all internal types and people would find the batching functionality more easily by reading the `futures` documentation or through code-completion. On the other hand, it might get harder to do breaking changes in the future and I'm not sure if we already reached that point of stability. I'm also not a huge fan of bigger crates for this kind of special functionality in the first place.

So I'd lean towards option 2, but I'd be interested in getting more opinions.

**Comment by leshow** [comment]
Sure, yeah, we could paste the new version in if you like-- I didn't realize it was 'out of sync'

**Pull request closed without merging**
